services:
    postgres:
        image: postgres:alpine
        container_name: ascc_database
        command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
        environment:
            POSTGRES_USER: ascc
            POSTGRES_PASSWORD: ascc_root
            POSTGRES_DB: ascc
        ports:
            - "5432:5432"
        networks:
            - ascc-network
        volumes:
            - pg_data:/var/lib/postgresql
        restart: on-failure:3

    app:
        build:
            context: backend
            dockerfile: Dockerfile
        env_file:
            - .env
        container_name: ascc_backend
        ports:
            - "8080:8080"
        networks:
            - ascc-network
        volumes:
            - ./backend/app:/code/app
        depends_on:
            - postgres
        restart: on-failure:3

volumes:
  pg_data:

networks:
  ascc-network: